/*
 * QRZ XML Logbook Data Specification
 *
 * This document describes the interface specification for access to QRZ's XML subscription data service. This service provides real-time access to information from the QRZ.COM servers and databases. Access to this service requires user authentication through the use of a valid QRZ.COM username and password. While any QRZ user may login to the service, an active QRZ Logbook Data subscription is required to access most of its features. Non-subscriber access limits the data fields that are returned and is primarily intended for testing and troubleshooting purposes only. A description of subscription plans and rates is available on the [QRZ website](http://www.qrz.com/i/subscriptions.html).
 *
 * API version: 1.34
 * Contact: va7stv@qrz.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package qrz

// QrzDatabase struct for QrzDatabase
type QrzDatabase struct {
	Session  Session  `json:"Session,omitempty" xml:"Session"`
	Callsign Callsign `json:"Callsign,omitempty" xml:"Callsign"`
	DXCC     Dxcc     `json:"DXCC,omitempty" xml:"DXCC"`
}
