/*
 * QRZ XML Logbook Data Specification
 *
 * This document describes the interface specification for access to QRZ's XML subscription data service. This service provides real-time access to information from the QRZ.COM servers and databases. Access to this service requires user authentication through the use of a valid QRZ.COM username and password. While any QRZ user may login to the service, an active QRZ Logbook Data subscription is required to access most of its features. Non-subscriber access limits the data fields that are returned and is primarily intended for testing and troubleshooting purposes only. A description of subscription plans and rates is available on the [QRZ website](http://www.qrz.com/i/subscriptions.html).
 *
 * API version: 1.34
 * Contact: va7stv@qrz.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package qrz

// Dxcc struct for Dxcc
type Dxcc struct {
	// DXCC entity number for this record
	Dxcc string `json:"dxcc,omitempty" xml:"dxcc"`
	// 2-letter country code (ISO-3166)
	Cc string `json:"cc,omitempty" xml:"cc"`
	// 3-letter country code (ISO-3166)
	Ccc string `json:"ccc,omitempty" xml:"ccc"`
	// long name
	Name string `json:"name,omitempty" xml:"name"`
	// 2-letter continent designator
	Continent string `json:"continent,omitempty" xml:"continent"`
	// ITU Zone
	Ituzone string `json:"ituzone,omitempty" xml:"ituzone"`
	// CQ Zone
	Cqzone string `json:"cqzone,omitempty" xml:"cqzone"`
	// timezone offset +/- UTC in hours. Odd timezones, such as 0545 mean \"5 hours, 45 minutes\". The plus (+) sign is implied.
	Timezone int32 `json:"timezone,omitempty" xml:"timezone"`
	// Latitude (approx.)
	Lat float64 `json:"lat,omitempty" xml:"lat"`
	// Longitude (approx.)
	Lon float64 `json:"lon,omitempty" xml:"lon"`
	// Special notes and/or exceptions
	Notes string `json:"notes,omitempty" xml:"notes"`
}
