name: Publish
on: workflow_dispatch

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.14.x

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        run: |
          go test ./...
          go vet ./...

      - name: Version Bump
        id: version-bump
        uses: phips28/gh-action-bump-version@v9.0.16
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag-prefix: 'v'

      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.version-bump.outputs.newTag }}
          release_name: ${{ steps.version-bump.outputs.newTag }}
